export const gameMetas = [
  {
    name: "Poopy Bird",
    imageSrc: "",
    isNew: true,
  },
  {
    name: "死亡地带",
    imageSrc: "",
    isNew: true,
  },
  {
    name: "Belt Rush",
    imageSrc: "",
    isNew: false,
  },
  {
    name: "吃土",
    imageSrc: "",
    isNew: false,
  },
  {
    name: "Poopy Bird2",
    imageSrc: "",
    isNew: false,
  },
  {
    name: "死亡地带2",
    imageSrc: "",
    isNew: false,
  },
  {
    name: "Belt Rush2",
    imageSrc: "",
    isNew: false,
  },
  {
    name: "吃土2",
    imageSrc: "",
    isNew: false,
  },
];

export const feed = [
  {
    id: 1,
    category: "游戏库",
    imageSrc: "/examples/IntoSoil.webp",
    author: "张三",
    publishTime: new Date(2024, 2, 14),
    title: "帖子标题：滚滚长江东是谁",
    content:
      "Lorem ipsum dolor sit amet consectetur adipisicing elit. Temporibus repellendus quos dolores quia cumque ducimus. Eos quo, natus eum, cum quasi modi sapiente eaque aut voluptas voluptatem nostrum omnis in.",
    tags: ["开发", "入门", "策划"],
    comments: ["LZSB", "沙发", "地板"],
    likes: 56,
    reading: 2,
  },
  {
    id: 2,
    category: "游戏库",
    imageSrc: "",
    author: "张三",
    publishTime: new Date(2024, 2, 14),
    title: "帖子标题：春江花月映楼台，噢噢噢噢",
    content:
      "Lorem ipsum dolor sit amet consectetur adipisicing elit. Temporibus repellendus quos dolores quia cumque ducimus. Eos quo, natus eum, cum quasi modi sapiente eaque aut voluptas voluptatem nostrum omnis in.",
    tags: ["开发", "入门", "策划"],
    comments: ["LZSB", "沙发", "地板"],
    likes: 56,
    reading: 2,
  },
  {
    id: 3,
    category: "游戏库",
    imageSrc: "/examples/IntoSoil.webp",
    author: "张三",
    publishTime: new Date(2024, 2, 14),
    title: "帖子标题：滚滚长江东是谁aaaaaaaaaaaaaa",
    content: "e eaque aut voluptas voluptatem nostrum omnis in.",
    tags: ["开发", "入门", "策划"],
    comments: ["LZSB", "沙发", "地板"],
    likes: 56,
    reading: 2,
  },
  {
    id: 4,
    category: "游戏库",
    imageSrc: "",
    author: "张三",
    publishTime: new Date(2024, 2, 14),
    title: "无标题",
    content:
      "Lorem ipsum dolor sit amet consectetur adipisicing elit. Temporibus repellendus quos dolores quia cumque ducimus. Eos quo, natus eum, cum quasi modi sapiente eaque aut voluptas voluptatem nostrum omnis in.",
    tags: ["开发", "入门", "策划"],
    comments: ["LZSB", "沙发", "地板"],
    likes: 56,
    reading: 2,
  },
  {
    id: 5,
    category: "游戏库",
    imageSrc: "",
    author: "张三",
    publishTime: new Date(2024, 2, 14),
    title: "帖子标题：滚滚长江东是谁",
    content:
      "Lorem ipsum dolor sit amet consectetur adipisicing elit. Temporibus repellendus quos dolores quia cumque ducimus. Eos quo, natus eum, cum quasi modi sapiente eaque aut voluptas voluptatem nostrum omnis in.",
    tags: ["开发", "入门", "策划"],
    comments: ["LZSB", "沙发", "地板"],
    likes: 56,
    reading: 2,
  },
  {
    id: 6,
    category: "游戏库",
    imageSrc: "",
    author: "张三",
    publishTime: new Date(2024, 2, 14),
    title: "帖子标题：滚滚长江东是谁",
    content:
      "Lorem ipsum dolor sit amet consectetur apiente eaque aut voluptas voluptatem nostrum omnis in.",
    tags: ["开发", "入门", "策划"],
    comments: ["LZSB", "沙发", "地板"],
    likes: 56,
    reading: 2,
  },
  {
    id: 7,
    category: "游戏库",
    imageSrc: "/examples/IntoSoil.webp",
    author: "张三",
    publishTime: new Date(2024, 2, 14),
    title: "帖子标题：滚23a",
    content:
      "Lorem ipsum dolor sit amet consectetur adipisicing elit. Temporibus repellendus quos dolores quia cumque ducimus. Eos quo, natus eum, cum quasi modi sapiente eaque aut voluptas voluptatem nostrum omnis in.",
    tags: ["开发", "入门", "策划"],
    comments: ["LZSB", "沙发", "地板"],
    likes: 56,
    reading: 2,
  },
  {
    id: 8,
    category: "游戏库",
    imageSrc: "",
    author: "张三",
    publishTime: new Date(2024, 2, 14),
    title: "帖子标题：滚滚长江东是谁",
    content: "Lorem ipsum doloraque aut voluptas voluptatem nostrum omnis in.",
    tags: ["开发", "入门", "策划"],
    comments: ["LZSB", "沙发", "地板"],
    likes: 56,
    reading: 2,
  },
];
